// src/components/GameList.vue
<script setup lang="ts">
interface product {
    id: number;
    name: string;
    href: string;
}
const products: product[] = [
    {
        id: 1,
        name: 'Mascote Cilarico',
        href: '/games/joguinho1/',
    },
]
</script>

<template>
    <div class="bg-white">
        <div class="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <h2 class="text-2xl font-bold tracking-tight text-gray-900">Customers also purchased</h2>

            <div class="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
                <div v-for="product in products" :key="product.id" class="group relative">
                    <div
                        class="min-h-80 aspect-w-1 aspect-h-1 w-full overflow-hidden rounded-md bg-gray-200 group-hover:opacity-75 lg:aspect-none lg:h-80">
                        <img :src="(product.href + 'thumb.jpg')" :alt="product.name"
                            class="h-full w-full object-cover object-center lg:h-full lg:w-full" />
                    </div>
                    <div class="mt-4 flex justify-between">
                        <div>
                            <h3 class="text-md text-slate-700 font-bold">
                                <a :href="(product.href + 'index.html')">
                                    <span aria-hidden="true" class="absolute inset-0" />
                                    {{ product.name }}
                                </a>
                            </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

// src/components/GameList.tsx
import React from 'react';
import GameCard from './GameCard'

interface Game {
    id: number;
    name: string;
    href: string;
    description: string;
}

const games: Game[] = [
    {
        id: 1,
        name: 'Mascote Cilarico',
        href: '/games/joguinho1/',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vestibulum, mauris vitae tincidunt aliquam, leo mauris tincidunt turpis, et malesuada felis nibh sed est.',
    },
    {
        id: 2,
        name: 'Jigsa Bilgiatan',
        href: '/games/joguinho1/',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vestibulum, mauris vitae tincidunt aliquam, leo mauris tincidunt turpis, et malesuada felis nibh sed est.',
    },
    {
        id: 3,
        name: 'Jigsa Bilgiatan',
        href: '/games/joguinho1/',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vestibulum, mauris vitae tincidunt aliquam, leo mauris tincidunt turpis, et malesuada felis nibh sed est.',
    },
    {
        id: 4,
        name: 'Jigsa Bilgiatan',
        href: '/games/joguinho1/',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vestibulum, mauris vitae tincidunt aliquam, leo mauris tincidunt turpis, et malesuada felis nibh sed est.',
    },
    {
        id: 5,
        name: 'Jigsa Bilgiatan',
        href: '/games/joguinho1/',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vestibulum, mauris vitae tincidunt aliquam, leo mauris tincidunt turpis, et malesuada felis nibh sed est.',
    },
    {
        id: 6,
        name: 'Jigsa Bilgiatan',
        href: '/games/joguinho1/',
        description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vestibulum, mauris vitae tincidunt aliquam, leo mauris tincidunt turpis, et malesuada felis nibh sed est.',
    }
]

const GameList: React.FC = () => {
    
    return (
    <div className="bg-white dark:bg-slate-600 transition-all">
        <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
            <h2 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-gray-300">Jogos Educacionais</h2>

            <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-3 xl:gap-x-8">
                {
                    games.map((game: Game, index) => (
                        <div key={index} className="group relative">
                            <GameCard key={game.id} game={game} />
                        </div>
                    ))
                }
            </div>
        </div>
    </div>)
}

export default GameList
